# --- Exchange Simulator defaults ---

fees:
  maker_bps: 2      # 0.02% (maker)
  taker_bps: 4      # 0.04% (taker)

# Slippage "pesimista" aplicado por los fill models (en bps)
slippage_bps: 1

account:
  starting_balance: 100000.0   # USDT inicial para backtests/replay

backtest_defaults:
  data_source: api             # api | files
  fill_model: ohlc_up          # ohlc_up | ohlc_down | random | book
  seed: 42                     # semilla RNG para modelos aleatorios
  apply_funding: true          # si hay datos de funding, aplicarlos

data:
  # Directorio base para usar con data.binance.vision (cuando data_source=files)
  binance_data_dir: ./data/binance

duckdb:
  path: data/duckdb/exsim.duckdb

# (Opcional, reservado)
# position_mode: oneway        # oneway | hedge
# validations:
#   tickSize: null
#   stepSize: null
#   minNotional: null
